version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Limits memory usage
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data  # Persistent storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      retries: 3

  unomi:
    image: apache/unomi:1.5.7
    container_name: unomi
    environment:
      - UNOMI_ELASTICSEARCH_ADDRESSES=http://elasticsearch:9200
      - UNOMI_THIRDPARTY_PROVIDER1_IPADDRESSES=0.0.0.0/0,::1,127.0.0.1
    ports:
      - "8181:8181"
      - "9443:9443"
      - "8102:8102"
    depends_on:
      elasticsearch:
        condition: service_healthy  # Wait for Elasticsearch to be ready

    volumes:
      esdata:
        driver: local


  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mautic
      - MYSQL_DATABASE=mautic
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -pmautic"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  mautic:
    image: mautic/mautic:v4-apache
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      - MAUTIC_DB_HOST=mysql
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=mautic
      - MAUTIC_DB_NAME=mautic
    volumes:
      - ./mautic-config:/var/www/html/app/config
    restart: unless-stopped

  middleware:
    build: ./middleware
    ports:
      - "3000:3000"
    depends_on:
      - unomi
      - mautic
    environment:
      - UNOMI_URL=http://unomi:8181
      - MAUTIC_URL=http://mautic:80
    restart: unless-stopped

volumes:
  es-data:
  mysql-data: